---
paths:
  '/orders/{id}/':
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                foodSelection:
                  description: foodSelection of this PlaceOrder
                  type: string
                quantity:
                  description: quantity of this PlaceOrder
                  type: integer
                specialRequest:
                  description: specialRequest of this PlaceOrder
                  type: string
                deliveryAddress:
                  description: deliveryAddress of this PlaceOrder
                  type: string
                paymentMethod:
                  description: paymentMethod of this PlaceOrder
                  type: string
            examples: null
      parameters:
        - name: id
          description: PlaceOrder name
          schema:
            type: string
          in: path
          required: true
          examples: null
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
              examples:
                '1':
                  value:
                    orderId: A string
                    foodSelection: A string
                    quantity: 1
                    specialRequest: A string
                    deliveryAddress: value
                    paymentMethod: A string
                    paymentMethodType: value
                    orderAmount: value
                    orderStatus: A string
                    estimatedDeliveryTime: A string
          description: PlaceOrder Operation
      operationId: PlaceOrder
      summary: PlaceOrder
      description: PlaceOrder
    summary: CancelOrder operation on orders
  /orders:
    summary: Global operations on orders
    get:
      tags:
        - orders
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
              examples:
                orders_json:
                  value:
                    - orderId: A string
                      foodSelection: A string
                      quantity: 1
                      specialRequest: A string
                      deliveryAddress: value
                      paymentMethod: A string
                      paymentMethodType: value
                      orderAmount: value
                      orderStatus: A string
                      estimatedDeliveryTime: A string
          description: Get list of orders
      operationId: GetOrder
      summary: Get list of orders
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
            examples:
              '1':
                value:
                  orderId: A string
                  foodSelection: A string
                  quantity: 1
                  specialRequest: A string
                  deliveryAddress: value
                  paymentMethod: A string
                  paymentMethodType: value
                  orderAmount: value
                  orderStatus: A string
                  estimatedDeliveryTime: A string
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
              examples:
                '1':
                  value:
                    orderId: A string
                    foodSelection: A string
                    quantity: 1
                    specialRequest: A string
                    deliveryAddress: value
                    paymentMethod: A string
                    paymentMethodType: value
                    orderAmount: value
                    orderStatus: A string
                    estimatedDeliveryTime: A string
          description: Changed Order
      operationId: Post Order
      summary: Post Order
  '/orders/{id}':
    summary: Specific operation on orders
    get:
      parameters:
        - examples:
            A string:
              value: A string
          name: id
          description: Order name
          schema:
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
              examples:
                '1':
                  value:
                    orderId: A string
                    foodSelection: A string
                    quantity: 1
                    specialRequest: A string
                    deliveryAddress: value
                    paymentMethod: A string
                    paymentMethodType: value
                    orderAmount: value
                    orderStatus: A string
                    estimatedDeliveryTime: A string
          description: orders with specified id
      operationId: GetOrderById
      summary: Get Order by id
      description: Get Order by id
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
            examples:
              '1':
                value:
                  orderId: A string
                  foodSelection: A string
                  quantity: 1
                  specialRequest: A string
                  deliveryAddress: value
                  paymentMethod: A string
                  paymentMethodType: value
                  orderAmount: value
                  orderStatus: A string
                  estimatedDeliveryTime: A string
        required: true
      parameters:
        - examples:
            '1':
              value: 1
          name: orderId
          description: Order name
          schema:
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
              examples:
                '1':
                  value:
                    orderId: A string
                    foodSelection: A string
                    quantity: 1
                    specialRequest: A string
                    deliveryAddress: value
                    paymentMethod: A string
                    paymentMethodType: value
                    orderAmount: value
                    orderStatus: A string
                    estimatedDeliveryTime: A string
          description: Changed Order
      operationId: PatchOrder
      summary: Patch existing Order
    parameters:
      - name: id
        description: Order id
        schema:
          type: string
        in: path
        required: true
openapi: 3.0.2
info:
  title: Order
  version: 0.0.1
  description: API definition of order
  contact:
    name: creator's name
    url: 'http://creator.homepage.address'
    email: creator@creator.com
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'
components:
  schemas:
    Order:
      title: Root Type for Order
      description: The root of the Order type's schema.
      type: object
      properties:
        orderId:
          description: orderId of this Order
          type: string
        foodSelection:
          description: foodSelection of this Order
          type: string
        quantity:
          description: quantity of this Order
          type: integer
        specialRequest:
          description: specialRequest of this Order
          type: string
        deliveryAddress:
          description: deliveryAddress of this Order
          type: string
        paymentMethod:
          description: paymentMethod of this Order
          type: string
        paymentMethodType:
          description: paymentMethodType of this Order
          type: string
        orderAmount:
          description: orderAmount of this Order
          type: string
        orderStatus:
          description: orderStatus of this Order
          type: string
        estimatedDeliveryTime:
          description: estimatedDeliveryTime of this Order
          type: string
tags:
  - name: Order
    description: Order resource
