---
paths:
  '/riders/{id}/':
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  description: orderId of this AcceptOrder
                  type: string
            examples: null
      parameters:
        - name: id
          description: AcceptOrder name
          schema:
            type: string
          in: path
          required: true
          examples: null
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rider'
              examples:
                '1':
                  value:
                    riderId: A string
                    riderName: A string
                    riderStatus: A string
          description: AcceptOrder Operation
      operationId: AcceptOrder
      summary: AcceptOrder
      description: AcceptOrder
    summary: MarkDeliveryCompleted operation on riders
  /riders:
    summary: Global operations on riders
    get:
      tags:
        - riders
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rider'
              examples:
                riders_json:
                  value:
                    - riderId: A string
                      riderName: A string
                      riderStatus: A string
          description: Get list of riders
      operationId: GetRider
      summary: Get list of riders
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rider'
            examples:
              '1':
                value:
                  riderId: A string
                  riderName: A string
                  riderStatus: A string
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rider'
              examples:
                '1':
                  value:
                    riderId: A string
                    riderName: A string
                    riderStatus: A string
          description: Changed Rider
      operationId: Post Rider
      summary: Post Rider
  '/riders/{id}':
    summary: Specific operation on riders
    get:
      parameters:
        - examples:
            A string:
              value: A string
          name: id
          description: Rider name
          schema:
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rider'
              examples:
                '1':
                  value:
                    riderId: A string
                    riderName: A string
                    riderStatus: A string
          description: riders with specified id
      operationId: GetRiderById
      summary: Get Rider by id
      description: Get Rider by id
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rider'
            examples:
              '1':
                value:
                  riderId: A string
                  riderName: A string
                  riderStatus: A string
        required: true
      parameters:
        - examples:
            '1':
              value: 1
          name: riderId
          description: Rider name
          schema:
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rider'
              examples:
                '1':
                  value:
                    riderId: A string
                    riderName: A string
                    riderStatus: A string
          description: Changed Rider
      operationId: PatchRider
      summary: Patch existing Rider
    parameters:
      - name: id
        description: Rider id
        schema:
          type: string
        in: path
        required: true
openapi: 3.0.2
info:
  title: Rider
  version: 0.0.1
  description: API definition of rider
  contact:
    name: creator's name
    url: 'http://creator.homepage.address'
    email: creator@creator.com
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'
components:
  schemas:
    Rider:
      title: Root Type for Rider
      description: The root of the Rider type's schema.
      type: object
      properties:
        riderId:
          description: riderId of this Rider
          type: string
        riderName:
          description: riderName of this Rider
          type: string
        riderStatus:
          description: riderStatus of this Rider
          type: string
tags:
  - name: Rider
    description: Rider resource
